name: cryptosafe_mobile
description: Native Flutter Android app for CryptoSafe.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  file_picker: ^8.1.2
  just_audio: ^0.9.40
  flutter_secure_storage: ^9.2.2
  sqflite_sqlcipher: ^3.1.0
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
